services:
    encurtador:
        container_name: encurtador
        image: hyperf/hyperf:8.3-alpine-v3.20-swoole
        working_dir: /app
        entrypoint: >
            /bin/sh -c "
                composer install &&
                cp .env.example .env &&
                php bin/hyperf.php migrate &&
                php bin/hyperf.php server:watch
            "
        volumes:
            - ./:/app
        ports:
            - 9501:9501
        depends_on:
            - encurtador-pgsql
            - encurtador-redis

    encurtador-pgsql:
        container_name: encurtador-pgsql
        image: postgres:latest
        environment:
            POSTGRES_USER: encurtador
            POSTGRES_PASSWORD: encurtador
            POSTGRES_DB: encurtador
        ports:
            - 5432:5432

    encurtador-redis:
        container_name: encurtador-redis
        image: redis:latest
        ports:
            - 6379:6379

networks:
  default:
    name: encurtador