name: Run Tests with Composer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with Docker Compose
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: encurtador
          command: composer test
          entrypoint: /bin/sh -c "composer install && composer test"

