name: Run Tests with Composer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests with Docker Compose
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: docker-compose.yml
          service: encurtador
          command: |
            /bin/sh -c "
              composer install &&
              cp .env.example .env &&
              php bin/hyperf.php migrate &&
              composer test
            "
