name: Run Tests with Composer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests with Docker Compose
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          compose-file: ./docker-compose.yml
          service-name: encurtador
          test-command: composer test
          timeout: 300

      - name: Shutdown Docker containers
        run: |
          docker-compose down
