name: Run Tests with Composer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests with Docker Compose
        uses: jmalvarezf-lmes/docker-compose-action@v1.4.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: "encurtador"
          test-command: "composer test"
